#!/bin/bash
# 🚀 DEPLOY SCRIPT - Portafolio a GitHub y Vercel

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║         🚀 PORTAFOLIO - SCRIPT DE DEPLOY FINAL               ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Colores para output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}PASO 1: PREPARACIÓN LOCAL${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${GREEN}✓${NC} Git inicializado"
echo -e "${GREEN}✓${NC} Archivos de test eliminados"
echo -e "${GREEN}✓${NC} README.md creado"
echo -e "${GREEN}✓${NC} .gitignore mejorado"
echo -e "${GREEN}✓${NC} Primer commit realizado"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}PASO 2: GITHUB (HACER MANUALMENTE)${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo "1. Ve a: https://github.com/new"
echo "   - Nombre: portfolio"
echo "   - Descripción: Portafolio personal con Next.js y Sanity CMS"
echo "   - Tipo: Public"
echo "   - NO inicialices con README"
echo "   - Click: Create repository"
echo ""
echo "2. Copia tu GITHUB_USERNAME de aquí: https://github.com/settings/profile"
echo ""
echo "3. Ejecuta estos comandos:"
echo -e "${YELLOW}   git branch -M main${NC}"
echo -e "${YELLOW}   git remote add origin https://github.com/GITHUB_USERNAME/portfolio.git${NC}"
echo -e "${YELLOW}   git push -u origin main${NC}"
echo ""
echo "   (Reemplaza GITHUB_USERNAME con tu usuario)"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}PASO 3: SANITY (IMPORTANTE - HACER ANTES DE VERCEL)${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo "1. Ejecuta Sanity Studio:"
echo -e "${YELLOW}   npm run studio${NC}"
echo ""
echo "2. Completa estos documentos (EN ESTE ORDEN):"
echo "   ☐ Hero Section"
echo "   ☐ About Section"
echo "   ☐ Skills & SkillGroups"
echo "   ☐ Projects (mínimo 1)"
echo "   ☐ Contact Info (IMPORTANTE: subir imagen en cvPreviewImage)"
echo ""
echo "3. Publica todos los documentos"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}PASO 4: VERCEL (DEPLOY FINAL)${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo "1. Ve a: https://vercel.com/dashboard"
echo "   - Login con GitHub"
echo ""
echo "2. Click: 'Add New...' → 'Project'"
echo ""
echo "3. Selecciona tu repositorio 'portfolio'"
echo ""
echo "4. Agrega Variables de Entorno (IMPORTANTE):"
echo -e "${YELLOW}   NEXT_PUBLIC_SANITY_PROJECT_ID${NC}=tu_project_id"
echo -e "${YELLOW}   NEXT_PUBLIC_SANITY_DATASET${NC}=production"
echo -e "${YELLOW}   NEXT_PUBLIC_SANITY_API_VERSION${NC}=2024-01-01"
echo -e "${YELLOW}   SANITY_READ_TOKEN${NC}=tu_read_token"
echo ""
echo "   (Obtén estos valores de: https://manage.sanity.io/projects)"
echo ""
echo "5. Click: 'Deploy'"
echo "   Espera 5-10 minutos"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}VERIFICACIÓN FINAL${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Después de desplegar, verifica:"
echo ""
echo "☐ Accede a tu URL de Vercel (ej: portfolio-chi.vercel.app)"
echo "☐ El portafolio carga correctamente"
echo "☐ Sanity content se ve (About, Projects, Contact)"
echo "☐ Imagen de CV aparece en la sección Recursos"
echo "☐ Responsivo en móvil, tablet y desktop"
echo "☐ Links funcionales (LinkedIn, GitHub, Email)"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}DOMINIO PERSONALIZADO (OPCIONAL)${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo "Si tienes un dominio personalizado:"
echo ""
echo "1. En Vercel → Tu Proyecto → Settings → Domains"
echo "2. Click: 'Add Domain'"
echo "3. Ingresa tu dominio (ej: enriquemanterola.com)"
echo "4. Sigue instrucciones para DNS"
echo "5. Espera 24-48 horas para que se propague"
echo ""

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}✨ ¡LISTO! Tu portafolio estará en producción muy pronto ✨${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo "📚 Documentación útil:"
echo "   - README.md (toda la info)"
echo "   - GITHUB_SETUP.md (GitHub setup)"
echo "   - VERCEL_DEPLOY.md (Vercel deployment)"
echo "   - COMPLETITUD.md (estado del proyecto)"
echo ""
echo "📞 ¿Dudas? Revisa README.md sección de Troubleshooting"
echo ""
